-- USER
INSERT INTO PERSON (FIRST_NAME,LAST_NAME,USER_NAME,PERSON_TYPE,PASSWORD,EMAIL,ENABLED) VALUES ('Janek','Kowalski','zaq','ROLE_USER' ,'$2a$10$xIz0W9ho4qLovINgQCCffOMEDffrPUJU.Y.zFsf4ep5rqjDL0nZoa','zaq@op.pl',true);
INSERT INTO PERSON (FIRST_NAME,LAST_NAME,USER_NAME,PERSON_TYPE,PASSWORD,EMAIL,ENABLED) VALUES ('Tobiasz','Nowak','XSW', 'ROLE_USER', '456', 'xsw@wp.pl',true);
INSERT INTO PERSON (FIRST_NAME,LAST_NAME,USER_NAME,PERSON_TYPE,PASSWORD,EMAIL,ENABLED) VALUES ('Wojciech','Sikorski','CDE', 'ROLE_USER', '789', 'cde@interia.pl',true);
INSERT INTO PERSON (FIRST_NAME,LAST_NAME,USER_NAME,PERSON_TYPE,PASSWORD,EMAIL,ENABLED) VALUES ('Anna','Lewandowska','VFR', 'ROLE_USER', '098','vfr@o2.pl',true);
INSERT INTO PERSON (FIRST_NAME,LAST_NAME,USER_NAME,PERSON_TYPE,PASSWORD,EMAIL,ENABLED) VALUES ('Piotr','Sztaba','BGT', 'ROLE_USER','765','bgt@gmail.com',true);
INSERT INTO PERSON (FIRST_NAME,LAST_NAME,USER_NAME,PERSON_TYPE,PASSWORD,EMAIL,ENABLED) VALUES ('Dawid','Węgiel','NHY', 'ROLE_ADMIN','432','nhy@microsoft.pl',true);

-- CHARGER
INSERT INTO CHARGER(NAME, ADDRESS, HEADQUARTERS) VALUES ('ORANGE', 'Al. Jerozolimskie 160', 'Warszawa');
INSERT INTO CHARGER(NAME, ADDRESS, HEADQUARTERS) VALUES ('Orlen', 'ul.Wiejska 3', 'WARSZAWA');
INSERT INTO CHARGER(NAME, ADDRESS, HEADQUARTERS) VALUES ('Enea', 'ul. Pastelowa 8', 'Poznań');

-- HOUSEHOLD
INSERT INTO HOUSEHOLD (ADDRESS,CITY,CURRENT_BALANCE,NAME) VALUES ('Puławska 2', 'Warszawa', 2500, 'Dom w drzewach');
INSERT INTO HOUSEHOLD (ADDRESS,CITY,CURRENT_BALANCE,NAME) VALUES ('Jana Kazimierza 1', 'Rymań', 800, 'Chatka ogrodnika');
INSERT INTO HOUSEHOLD (ADDRESS,CITY,CURRENT_BALANCE,NAME) VALUES ('Szkolna 23/5', 'Janów Podlaski', 3000, 'Stajnia');
INSERT INTO HOUSEHOLD (ADDRESS,CITY,CURRENT_BALANCE,NAME) VALUES ('Kolorowa 44H', 'Sopot', 5000, 'Apartament Luxury');
INSERT INTO HOUSEHOLD (ADDRESS,CITY,CURRENT_BALANCE,NAME) VALUES ('al. Jerozolimskie 13', 'Warszawa', 10000, 'Apartament Prezydencki');


-- HOUSEHOLD_USERS
INSERT INTO HOUSEHOLD_USERS (HOUSEHOLD_ID ,PERSON_ID) VALUES (1,1);
INSERT INTO HOUSEHOLD_USERS (HOUSEHOLD_ID ,PERSON_ID) VALUES (1,2);
INSERT INTO HOUSEHOLD_USERS (HOUSEHOLD_ID ,PERSON_ID) VALUES (2,3);
INSERT INTO HOUSEHOLD_USERS (HOUSEHOLD_ID ,PERSON_ID) VALUES (3,4);
INSERT INTO HOUSEHOLD_USERS (HOUSEHOLD_ID ,PERSON_ID) VALUES (4,5);
INSERT INTO HOUSEHOLD_USERS (HOUSEHOLD_ID ,PERSON_ID) VALUES (5,6);

-- TRANSACTIONS_CATEGORY
INSERT INTO TRANSACTION_CATEGORY (TYPE) VALUES ('Jedzenie');
INSERT INTO TRANSACTION_CATEGORY (TYPE) VALUES ('Mieszkanie');
INSERT INTO TRANSACTION_CATEGORY (TYPE) VALUES ('Inne opłaty i rachunki');
INSERT INTO TRANSACTION_CATEGORY (TYPE) VALUES ('Zdrowie, higiena i chemia');
INSERT INTO TRANSACTION_CATEGORY (TYPE) VALUES ('Ubranie');
INSERT INTO TRANSACTION_CATEGORY (TYPE) VALUES ('Relaks');
INSERT INTO TRANSACTION_CATEGORY (TYPE) VALUES ('Transport');
INSERT INTO TRANSACTION_CATEGORY (TYPE) VALUES ('Gaz');
INSERT INTO TRANSACTION_CATEGORY (TYPE) VALUES ('Prąd');
INSERT INTO TRANSACTION_CATEGORY (TYPE) VALUES ('Woda');
INSERT INTO TRANSACTION_CATEGORY (TYPE) VALUES ('Śmieci');
INSERT INTO TRANSACTION_CATEGORY (TYPE) VALUES ('Wynagrodzenie');

-- TRANSACATIONS
-- INSERT INTO TRANSACTION
--     (ID, AMOUNT, DESCRIPTION, NAME, TRANSACTION_DATE, TRANSACTION_PAYMENT_DATE, TRANSACTION_PERIOD,
--     TRANSACTION_TYPE, TRANSACTION_CATEGORY_ID, CHARGER_ID, HOUSEHOLD_ID, PERSON_ID)
--     VALUES (1, 199.99, 'Kurtka dla syna', 'Kurtka', '2022-11-18', '2022-11-20', 'JEDNORAZOWA', 'KOSZT', 5, 2, 1, 2);
-- INSERT INTO TRANSACTION
--     (ID, AMOUNT, DESCRIPTION, NAME, TRANSACTION_DATE, TRANSACTION_PAYMENT_DATE, TRANSACTION_PERIOD,
--     TRANSACTION_TYPE, TRANSACTION_CATEGORY_ID, CHARGER_ID, HOUSEHOLD_ID, PERSON_ID)
--     VALUES (2, 25, 'Rachunek za telefon', 'Abonament tel', '2022-11-25', '2022-11-26', 'CYKLICZNA', 'KOSZT', 3, 1, 1, 2);
-- INSERT INTO TRANSACTION
--     (ID, AMOUNT, DESCRIPTION, NAME, TRANSACTION_DATE, TRANSACTION_PAYMENT_DATE, TRANSACTION_PERIOD,
--     TRANSACTION_TYPE, TRANSACTION_CATEGORY_ID, CHARGER_ID, HOUSEHOLD_ID, PERSON_ID)
--     VALUES (3, 500, 'Benzyna Pb95', 'Tankowanie', '2022-11-26', '2022-11-26', 'JEDNORAZOWA', 'KOSZT', 7, 2, 2, 1);
-- INSERT INTO TRANSACTION
--     (ID, AMOUNT, DESCRIPTION, NAME, TRANSACTION_DATE, TRANSACTION_PAYMENT_DATE, TRANSACTION_PERIOD,
--     TRANSACTION_TYPE, TRANSACTION_CATEGORY_ID, CHARGER_ID, HOUSEHOLD_ID, PERSON_ID)
--     VALUES (4, 25, 'Dodatek świąteczny', 'Wpływ', '2022-11-23', '2022-11-23', 'JEDNORAZOWA', 'DOCHOD', 11, null, 1, 1);

