-- USER
INSERT INTO PERSON (FIRST_NAME, LAST_NAME)
VALUES ('Janek', 'Kowalski');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME)
VALUES ('Tobiasz', 'Nowak');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME)
VALUES ('Wojciech', 'Sikorski');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME)
VALUES ('Anna', 'Lewandowska');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME)
VALUES ('Piotr', 'Sztaba');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME)
VALUES ('Dawid', 'Węgiel');

-- CHARGER
INSERT INTO CHARGER(NAME, ADDRESS, HEADQUARTERS)
VALUES ('ORANGE', 'Al. Jerozolimskie 160', 'Warszawa');
INSERT INTO CHARGER(NAME, ADDRESS, HEADQUARTERS)
VALUES ('Orlen', 'ul.Wiejska 3', 'WARSZAWA');
INSERT INTO CHARGER(NAME, ADDRESS, HEADQUARTERS)
VALUES ('Enea', 'ul. Pastelowa 8', 'Poznań');

-- HOUSEHOLD
INSERT INTO HOUSEHOLD (ADDRESS, CITY, CURRENT_BALANCE, NAME)
VALUES ('Puławska 2', 'Warszawa', 2500, 'Dom w drzewach');
INSERT INTO HOUSEHOLD (ADDRESS, CITY, CURRENT_BALANCE, NAME)
VALUES ('Jana Kazimierza 1', 'Rymań', 800, 'Chatka ogrodnika');
INSERT INTO HOUSEHOLD (ADDRESS, CITY, CURRENT_BALANCE, NAME)
VALUES ('Szkolna 23/5', 'Janów Podlaski', 3000, 'Stajnia');
INSERT INTO HOUSEHOLD (ADDRESS, CITY, CURRENT_BALANCE, NAME)
VALUES ('Kolorowa 44H', 'Sopot', 5000, 'Apartament Luxury');
INSERT INTO HOUSEHOLD (ADDRESS, CITY, CURRENT_BALANCE, NAME)
VALUES ('al. Jerozolimskie 13', 'Warszawa', 10000, 'Apartament Prezydencki');


-- HOUSEHOLD_USERS
INSERT INTO HOUSEHOLD_USERS (HOUSEHOLD_ID, PERSON_ID)
VALUES (1, 1);
INSERT INTO HOUSEHOLD_USERS (HOUSEHOLD_ID, PERSON_ID)
VALUES (1, 2);
INSERT INTO HOUSEHOLD_USERS (HOUSEHOLD_ID, PERSON_ID)
VALUES (2, 3);
INSERT INTO HOUSEHOLD_USERS (HOUSEHOLD_ID, PERSON_ID)
VALUES (3, 4);
INSERT INTO HOUSEHOLD_USERS (HOUSEHOLD_ID, PERSON_ID)
VALUES (4, 5);
INSERT INTO HOUSEHOLD_USERS (HOUSEHOLD_ID, PERSON_ID)
VALUES (5, 6);

-- TRANSACTIONS_CATEGORY
INSERT INTO TRANSACTION_CATEGORY (TYPE)
VALUES ('Jedzenie');
INSERT INTO TRANSACTION_CATEGORY (TYPE)
VALUES ('Mieszkanie');
INSERT INTO TRANSACTION_CATEGORY (TYPE)
VALUES ('Inne opłaty i rachunki');
INSERT INTO TRANSACTION_CATEGORY (TYPE)
VALUES ('Zdrowie, higiena i chemia');
INSERT INTO TRANSACTION_CATEGORY (TYPE)
VALUES ('Ubranie');
INSERT INTO TRANSACTION_CATEGORY (TYPE)
VALUES ('Relaks');
INSERT INTO TRANSACTION_CATEGORY (TYPE)
VALUES ('Transport');
INSERT INTO TRANSACTION_CATEGORY (TYPE)
VALUES ('Gaz');
INSERT INTO TRANSACTION_CATEGORY (TYPE)
VALUES ('Prąd');
INSERT INTO TRANSACTION_CATEGORY (TYPE)
VALUES ('Woda');
INSERT INTO TRANSACTION_CATEGORY (TYPE)
VALUES ('Śmieci');
INSERT INTO TRANSACTION_CATEGORY (TYPE)
VALUES ('Wynagrodzenie');

-- TRANSACATIONS
INSERT INTO TRANSACTION
(AMOUNT, DESCRIPTION, NAME, TRANSACTION_DATE, TRANSACTION_PAYMENT_DATE, TRANSACTION_PERIOD,
 TRANSACTION_TYPE, TRANSACTION_CATEGORY_ID, CHARGER_ID, HOUSEHOLD_ID, PERSON_ID)
VALUES (199.99, 'Kurtka dla syna', 'Kurtka', '2022-11-18', '2022-11-20', 'JEDNORAZOWA', 'KOSZT', 5, 2, 1, 2);
INSERT INTO TRANSACTION
(AMOUNT, DESCRIPTION, NAME, TRANSACTION_DATE, TRANSACTION_PAYMENT_DATE, TRANSACTION_PERIOD,
 TRANSACTION_TYPE, TRANSACTION_CATEGORY_ID, CHARGER_ID, HOUSEHOLD_ID, PERSON_ID)
VALUES (25, 'Rachunek za telefon', 'Abonament tel', '2022-11-25', '2022-11-26', 'CYKLICZNA', 'KOSZT', 3, 1, 1, 2);
INSERT INTO TRANSACTION
(AMOUNT, DESCRIPTION, NAME, TRANSACTION_DATE, TRANSACTION_PAYMENT_DATE, TRANSACTION_PERIOD,
 TRANSACTION_TYPE, TRANSACTION_CATEGORY_ID, CHARGER_ID, HOUSEHOLD_ID, PERSON_ID)
VALUES (500, 'Benzyna Pb95', 'Tankowanie', '2022-11-26', '2022-11-26', 'JEDNORAZOWA', 'KOSZT', 7, 2, 2, 1);
INSERT INTO TRANSACTION
(AMOUNT, DESCRIPTION, NAME, TRANSACTION_DATE, TRANSACTION_PAYMENT_DATE, TRANSACTION_PERIOD,
 TRANSACTION_TYPE, TRANSACTION_CATEGORY_ID, CHARGER_ID, HOUSEHOLD_ID, PERSON_ID)
VALUES (25, 'Dodatek świąteczny', 'Wpływ', '2022-11-23', '2022-11-23', 'JEDNORAZOWA', 'DOCHOD', 11, null, 1, 1);
INSERT INTO TRANSACTION
(AMOUNT, DESCRIPTION, NAME, TRANSACTION_DATE, TRANSACTION_PAYMENT_DATE, TRANSACTION_PERIOD,
 TRANSACTION_TYPE, TRANSACTION_CATEGORY_ID, CHARGER_ID, HOUSEHOLD_ID, PERSON_ID)
VALUES (4500, 'Wypłata', 'Wpływ', '2022-11-10', '2022-11-10', 'JEDNORAZOWA', 'DOCHOD', 11, null, 1, 1);
